version: "3.7"

services:
  web:
    image: psodstorage/api-consumer
    ports:
      - "8080:80"
    volumes:
      - "api-consumer-cache:/api-cache"
    networks:
      - api-consumer-net

volumes:
  api-consumer-cache:

networks:
  api-consumer-net: